# 异常体系

* java.lang.Throwable
  * java.lang.Error:一般不编写针对性的代码进行处理。
  * java.lang.Exception:可以进行异常的处理。
    * 编译时异常（checked）
      * IOException
        * FileNotFoundException
      * ClassNotFoundExeption
      * ...
    * 运行时异常（unchecked）
      * NullPointerException
      * ArrayIndexOutOfBoundsException
      * ClassCastException
      * NumberFormatException
      * InputMismatchException
      * ArithmeticException
      * ...

# 异常处理方式概述

* try-catch-finally
* throws

异常处理模型：抓抛模型。

* 过程一：“抛”：程序在执行过程中，一旦出现异常，就会在异常代码处生成一个对应异常类的对象，并且将次对象抛出，一旦抛出此对象，其后的代码就不再执行。
* 过程二：“抓”：可以理解为异常的处理方式：try-catch-finally和throws

# try-catch-finally的使用

try{

可能出现异常的代码

}catch(异常类型1 变量名1){

​	处理方式1

}catch(异常类型2 变量名2){

​	处理方式2

}catch(异常类型3 变量名3){

​	处理方式3

}

...

finally{

//一定会执行的代码

}

* finally是可选的。

* 使用try将可能出现异常的代码包装起来，在执行过程中，一旦出现异常，就会生成一个对应异常类的对象，根据此对象的类型，去catch中进行匹配。
* 一旦try中的异常对象匹配到某个catch时，就进入catch中进行异常处理。一旦处理完成，就跳出当前的try-catch结构（在没有编写finally的情况），继续执行其后的代码。
* catch中的异常类型如果没有子父类关系，则谁声明在上，谁声明在下无所谓。
* catch中的异常类型如果满足子父类关系，则要求子类一定声明在父类的上面，否则会报错。
* 异常常用的两个处理方式：
  * printStackTrace();
  * getMessage();
* 在try结构中声明的变量，出了try结构以后，就不能被调用。

* finally中声明的是一定会被执行的代码，即使catch中又出现异常了，try中有return语句，catch中有return语句等情况。
* 像数据库连接、输入输出流、网络编程Socket等资源，jvm是不能自动回收的，我们需要自己手动的进行资源的释放，此时的资源释放，就需要声明在finally中。

# throws的使用

异常处理方式二：throws + 异常类型

* 指明此方法执行时，可能会抛出的异常的类型，一旦当方法体执行时，出现异常，扔会在异常代码处生成一个异常类的对象，此对象满足throws后异常类型时，就会被抛出，异常代码的后续代码就不会执行。
* try-catch-finally是真正的将异常给处理掉了。
* throws的方式只是将异常抛给了方法的调用者，并没有真正将异常处理掉。
* 方法重写的规则：子类重写的方法抛出的异常类型不大于父类被重写的方法抛出的异常类型。

# throws和try-catch-finally的选择

开发中如何选择使用try-catch-finally和throws？

* 如果父类中被重写的方法没有throws方式处理异常，则子类重写的方法也不能使用throws，意味着如果子类重写的方法中有异常，必须使用try-catch-finally方式处理。
* 执行方法a中，先后又调用了另外的几个方法，这几个方法是递进关系执行的，建议这几个方法分别使用throws的方式进行处理，而执行的方法a可以考虑使用try-catch-finally方式进行处理。

# 手动抛出异常对象

~~~java
public class ThrowTest {
    public static void main(String[] args) {
        Student student = new Student();
        try {
            student.setId(-10);
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println(student);
    }

}

class Student{
    private int id;
    public void setId(int id) throws Exception {
        if(id>0)
            this.id = id;
        else
            throw new Exception("数据非法异常");
    }

    @Override
    public String toString() {
        return "Student{" +
                "id=" + id +
                '}';
    }
}
~~~

# 用户自定义异常类

如何自定义异常类？

* 继承于现有的异常结构：RuntimeException、Exception。
* 提供全局常量：serialVersionUID.
* 提供重载的构造器。